### ISSUE TITLE
App crashes just before getting a lock

### ISSUE THREAD

**Issue by ravilov** [woheller69/gpscockpit#9]
I'm getting this in logcat:

```
java.lang.AbstractMethodError: abstract method "void android.location.LocationListener.onStatusChanged(java.lang.String, int, android.os.Bundle)"
	at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:304)
	at android.location.LocationManager$ListenerTransport.-wrap0(LocationManager.java)
	at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:242)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6176)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```

Android 7.1.1, if that matters.

**Comment by woheller69** [comment]
I think I found the bug.
Can you please try the attached app? (Just remove .zip and install)
In case of a crash please go to Android/data/org.woheller69/gpscockpit/files in internal memory and upload the crashlog file.

[app-debug.apk.zip](https://github.com/woheller69/gpscockpit/files/7805859/app-debug.apk.zip)

**Comment by ravilov** [comment]
Just tried it, this one gets a lock and doesn't crash. Thanks
